version: "3.4"

services:
  frontend:
    build:
      context: /../../
      dockerfile: /ci/dockerfiles/Frontend.Dockerfile
    environment:
      - NODE_ENV = development
    ports:
      - "3000:80"
    volumes:
      - .:/app