version: "3.4"

services:
  frontend:
    container_name: frontend
    build:
      context: /../../
      dockerfile: /ci/dockerfiles/Frontend.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:80"
    networks:
      - itcamp_network
    volumes:
      - .:/app

networks:
  itcamp_network:
    external: true